### ISSUE TITLE
Page Collection Error for some Mangadex URLs

### ISSUE THREAD

**Issue by gtache** [HDoujinDownloader/HDoujinDownloader#370]
Hi,       
Some URLs on Mangadex cause an error even though chapters are present. Examples:     
https://mangadex.org/title/6b1eb93e-473a-4ab3-9922-1a66d2a29a4a/naruto       
https://mangadex.org/title/a77742b1-befd-49a4-bff5-1ad4e6b0ef7b/chainsaw-man         
https://mangadex.org/title/15b458ec-71fc-40b0-af60-656d0904490e/air-gear

I don't see a pattern that would explain why these fail given that a lot of other URLs work correctly.     

Thank you for the program by the way!

**Comment by HDoujinDownloader** [comment]
This _might_ be resolved with the fix I uploaded a couple of days ago. When I checked out the provided URLs, I was encountering errors due to MangaDex rate-limiting the API requests when enumerating the chapter lists. I updated the module to request the maximum number of chapters per request to reduce the chance of getting rate-limited.

Let me know if the problem is resolved for you!

**Comment by gtache** [comment]
Unfortunately I still get the same error, here is the log I get when retrying to download Naruto: [1720383316.log](https://github.com/user-attachments/files/16120650/1720383316.log)

**Comment by gtache** [comment]
Bumping this issue because I'm still having the same problem. Some examples:
- https://mangadex.org/title/15b458ec-71fc-40b0-af60-656d0904490e/air-gear
- https://mangadex.org/title/a77742b1-befd-49a4-bff5-1ad4e6b0ef7b/chainsaw-man  
- https://mangadex.org/title/239d6260-d71f-43b0-afff-074e3619e3de

**Comment by HDoujinDownloader** [comment]
Investigating this (thanks a lot for including the log file!). I tried some of the URLs you provided, and while I did run into some rate-limiting issues here and there, I don't think I encountered the problem you're experiencing.

According to the log file, it's getting a 404 error when attempting to access certain chapters. All the chapters ran threw successfully for me, though.

One thing they all have in common is that they have a _lot_ of chapters. Does it seem to happen consistently for lengthy content? Are there any particular chapters that consistently fail?

**Comment by gtache** [comment]
I also thought it was due to the number of chapters, but it doesn't seem to be the case given that others like https://mangadex.org/title/d7037b2a-874a-4360-8a7b-07f2899152fd/mairimashita-iruma-kun, https://mangadex.org/title/e52d9403-3356-403b-b7bb-d7d6a420dd50/nanatsu-no-taizai or https://mangadex.org/title/40bc649f-7b49-4645-859e-6cd94136e722/dragon-ball worked perfectly.
I also tried adding my login credentials in the settings but it changes nothing.    

It's quite strange that you get a different behavior given that it seems to be due to "missing" chapters...
I'm attaching a more recent log, although I don't think it gives any more info than the previous one:
[1743972170-debug.log](https://github.com/user-attachments/files/19623451/1743972170-debug.log)

Thanks again for your help!
